spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL.SENDER}
    password: ${MAIL.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 300000  # 5 * 60 * 1000(밀리초) == 5분
  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}
      password: ${REDIS.PASSWORD}
      time_to_live:
        likes: 86400 # 24h
        liked: 86400 # 24h
        matching: 3600 # 1h
        data: 604800 # 1주일
        rank: 604800 # 1주일
        detail: 86400 # 1일
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE.URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE.CLIENT_ID}
            client-secret: ${GOOGLE.SECURITY_PASSWORD}
            scope:
              - profile
              - email
            redirect-uri: https://api.app.mm.ts0608.life/login/oauth2/code/google

jwt:
  secret: ${JWT.SECRET}
  expiration:
    access-token: ${JWT.EXPIRATION.ACCESS_TOKEN}
    refresh-token: ${JWT.EXPIRATION.REFRESH_TOKEN}
  cookie-domain: ${JWT.COOKIE_DOMAIN}
  cookie-path: ${JWT.COOKIE_PATH}


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    orh.hibernate.orm.jdbc.extract: trace
    org.springframework.transaction.interceptor: trace

movie:
  api:
    kofic_key: ${MOVIE.API.KEY}
    tmdb_key: ${MOVIE.API.KEY2}
    rank-url: "https://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchWeeklyBoxOfficeList.json"
    detail-url: "https://www.kobis.or.kr/kobisopenapi/webservice/rest/movie/searchMovieInfo.json"
    tmdb-search-url: "https://api.themoviedb.org/3/search/movie"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus  # Prometheus 메트릭을 수집
  metrics:
    web:
      enabled: true  # Web 메트릭을 활성화
  health:
    indicators:
      diskspace:
        enabled: true  # 디스크 공간 모니터링
      db:
        enabled: true  # DB 모니터링
      redis:
        enabled: true  # Redis 모니터링
  web:
    description: "Backend Service Monitoring"  # 서비스 설명
  prometheus:
    metrics:
      export:
        enabled: true
        step: 1m

prometheus:
  endpoint: /actuator/prometheus  # Prometheus 메트릭 노출 경로
  scrape-interval: 10s  # Prometheus에서 메트릭을 얼마나 자주 가져올지 (10초마다)
