server:
  port: 8080  # ✅ 서버 포트 조정 가능 (예: 8080 → 8081)
  shutdown: graceful
  tomcat:
    max-swallow-size: 1GB  # ✅ 업로드 용량 제한 가능
    max-http-form-post-size: 1GB  # ✅ POST 요청 크기 제한

spring:
  profiles:
    active: dev
    include: secret  # ✅ 추가 설정 파일 포함

logging:
  level:
    org.hibernate.SQL: DEBUG  # ✅ 로그 레벨 조정 가능 (INFO, DEBUG, TRACE 등)
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  appName: app.mm  # ✅ 앱 이름 변경 가능
  prod:
    domain: ts0608.life  # ✅ 운영 도메인 변경 가능
    backUrl: "https://api.${custom.appName}.${custom.prod.domain}"
    frontUrl: "https://www.${custom.appName}.${custom.prod.domain}"

  dev:
    domain: localhost  # ✅ 개발 도메인 변경 가능
    backUrl: "http://${custom.dev.domain}:${server.port}"
    frontUrl: "http://${custom.dev.domain}:3000"

  site:
    domain: "${custom.prod.domain}"
    backUrl: "${custom.prod.backUrl}"
    frontUrl: "${custom.prod.frontUrl}"

  genFile:
    dirPath: c:/temp/glog_dev  # ✅ 파일 저장 경로 (리눅스면 /tmp 등으로 변경 가능)