spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL.SENDER}
    password: ${MAIL.PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 300000  # 5 * 60 * 1000(밀리초) == 5분
  config:
    import: application-secret.yml
  datasource:
    url: ${DATABASE.URL}  # ✅ 환경 변수로 MySQL 설정 가능
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE.CLIENT_ID}
            client-secret: ${GOOGLE.SECURITY_PASSWORD}
            scope:
              - profile
              - email
            redirect-uri: https://api.app.mm.ts0608.life/login/oauth2/code/google
  data:
    redis:
      host: redis_1
      port: 6379   # 기본값 6379
      time_to_live:
        likes: 86400 # 24h
        liked: 86400 # 24h
        matching: 3600 # 1h
  logging:
    level:
      com.example: INFO
      org.hibernate.SQL: INFO
      org.hibernate.orm.jdbc.bind: INFO
      org.hibernate.orm.jdbc.extract: INFO
      org.springframework.transaction.interceptor: INFO

  custom:
    site:
      domain: "${custom.prod.domain}"
      backUrl: "${custom.prod.backUrl}"
      frontUrl: "${custom.prod.frontUrl}"
    genFile:
      dirPath: /gen

  jwt:
    secret: ${JWT.SECRET}
    expiration:
      access-token: ${JWT.EXPIRATION.ACCESS_TOKEN}
      refresh-token: ${JWT.EXPIRATION.REFRESH_TOKEN}
    cookie-domain: ${JWT.COOKIE_DOMAIN} # 도메인
    cookie-path: ${JWT.COOKIE_PATH}
