spring:
  data:
    redis:
      host: ${REDIS.HOST}
      port: ${REDIS.PORT}
      time_to_live:
        likes: ${REDIS.TIME_TO_LIVE.likes}
        liked: ${REDIS.TIME_TO_LIVE.liked}
        matching: ${REDIS.TIME_TO_LIVE.matching}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE.URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE.CLIENT_ID}
            client-secret: ${GOOGLE.SECURITY_PASSWORD}
            scope:
              - profile
              - email

jwt:
  secret: ${JWT.SECRET}
  expiration:
    access-token: ${JWT.EXPIRATION.ACCESS_TOKEN}
    refresh-token: ${JWT.EXPIRATION.REFRESH_TOKEN}
  cookie-domain: ${JWT.COOKIE_DOMAIN}
  cookie-path: ${JWT.COOKIE_PATH}


logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.orm.jdbc.bind: trace
    orh.hibernate.orm.jdbc.extract: trace
    org.springframework.transaction.interceptor: trace