name: Backend CI & Deploy

on:
  pull_request:
    branches: [ main, develop ]
    types: [ opened, closed, synchronize ]
  push:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: schs

jobs:
  backend-ci:
    runs-on: ubuntu-latest
    outputs:
      test-result: ${{ steps.upload-test-report.outputs.artifact }}
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: moviematch
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Generate application-secret.yml
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_DEV_YML }}
        run: echo "$APPLICATION_SECRET" > backend/src/main/resources/application-secret.yml

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: backend/

      - name: Build with Gradle with test profile
        run: ./gradlew build -Dspring.profiles.active=test
        working-directory: backend/

      - name: Upload test report if it exists
        if: failure()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: test-report
          path: backend/build/reports/tests/test/
          if-no-files-found: ignore

  makeTagAndRelease:
    if: |
      (github.event_name == 'push' &&
       (github.ref == 'refs/heads/cd')) ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       (github.base_ref == 'main' || github.base_ref == 'develop'|| github.base_ref == 'cd'))
    runs-on: ubuntu-latest
    needs: backend-ci
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Create Tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false

  buildImageAndPush:
    if: |
      (github.event_name == 'push' &&
       (github.ref == 'refs/heads/cd')) ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       (github.base_ref == 'main' || github.base_ref == 'develop'|| github.base_ref == 'cd'))
    runs-on: ubuntu-latest
    needs: makeTagAndRelease
    outputs:
      owner_lc: ${{ steps.export_owner.outputs.owner_lc }}
      image_name: ${{ steps.export_image.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Generate application-secret.yml
        env:
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YML }}
        run: echo "$APPLICATION_SECRET" > backend/src/main/resources/application-secret.yml

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: ./backend/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Export owner and image name
        id: export_owner
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          echo "owner_lc=$OWNER_LC" >> $GITHUB_OUTPUT

      - name: Export image name
        id: export_image
        run: echo "image_name=schs" >> $GITHUB_OUTPUT

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.export_owner.outputs.owner_lc }}/${{ steps.export_image.outputs.image_name }}:${{ needs.makeTagAndRelease.outputs.tag_name }}
            ghcr.io/${{ steps.export_owner.outputs.owner_lc }}/${{ steps.export_image.outputs.image_name }}:latest

  deploy:
    if: |
      (github.event_name == 'push' &&
       (github.ref == 'refs/heads/cd')) ||
      (github.event_name == 'pull_request' &&
       github.event.pull_request.merged == true &&
       (github.base_ref == 'main' || github.base_ref == 'develop'|| github.base_ref == 'cd'))
    runs-on: ubuntu-latest
    needs: [ buildImageAndPush ]
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.AWS_EC2_ID }}
          working-directory: /
          comment: Deploy
          command: |
            IMAGE="ghcr.io/${{ needs.buildImageAndPush.outputs.owner_lc }}/${{ needs.buildImageAndPush.outputs.image_name }}:latest"
            VOLUME="/gen:/gen"
            NETWORK="common"
            HEALTH_ENDPOINT="/actuator/health"
            TIMEOUT=60

            if docker ps --format '{{.Names}}' | grep -q "app1_1"; then
              CURRENT="app1_1"
              NEXT="app1_2"
              CURRENT_PORT=8080
              NEXT_PORT=8081
            else
              CURRENT="app1_2"
              NEXT="app1_1"
              CURRENT_PORT=8081
              NEXT_PORT=8080
            fi

            echo "Pulling new image..."
            docker pull "$IMAGE"

            echo "Stopping previous $NEXT (if exists)"
            docker stop "$NEXT" 2>/dev/null || true
            docker rm "$NEXT" 2>/dev/null || true

            echo "Starting new container: $NEXT"
            docker run -d \
              -v $VOLUME \
              --network $NETWORK \
              --name "$NEXT" \
              -p "$NEXT_PORT":8080 \
              "$IMAGE"

            echo "Waiting for health check..."
            START_TIME=$(date +%s)
            while true; do
              CONTENT=$(curl -s http://localhost:$NEXT_PORT$HEALTH_ENDPOINT)

              if [[ "$CONTENT" == *'"status":"UP"'* ]]; then
                echo "✅ $NEXT is UP!"
                break
              fi

              ELAPSED_TIME=$(( $(date +%s) - START_TIME ))
              if [[ $ELAPSED_TIME -ge $TIMEOUT ]]; then
                echo "❌ Timeout: $NEXT did not start in $TIMEOUT seconds."
                docker stop "$NEXT"
                docker rm "$NEXT"
                exit 1
              fi

              echo "⏳ Waiting for $NEXT to be UP..."
              sleep 5
            done

            echo "Stopping old container: $CURRENT"
            docker stop "$CURRENT" 2>/dev/null || true
            docker rm "$CURRENT" 2>/dev/null || true

            echo "Cleaning up unused images..."
            docker rmi $(docker images -f "dangling=true" -q) 2>/dev/null || true

            echo "✅ Deployment complete. Running: $NEXT"